# AINDA EM CONSTRUCAO, NAO ESTA LENDO O TERMINAL

services:
  super-nodo-1:
    container_name: super-nodo-1
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.1
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.1
      - nextIp=10.1.1.2
      - hasToken=1


  super-nodo-2:
    container_name: super-nodo-2
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.2
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.2
      - nextIp=10.1.1.1
      - hasToken=0

networks:
  distribuida:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/8