# AINDA EM CONSTRUCAO, NAO ESTA LENDO O TERMINAL

services:
  super-node-1:
    container_name: super-node-1
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.1
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.1
      - nextIp=10.1.1.2
    entrypoint: java -jar build/libs/t1-p2p-1.jar

  super-node-2:
    container_name: super-node-2
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.2
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.2
      - nextIp=10.1.1.3
    entrypoint: java -jar build/libs/t1-p2p-1.jar

  super-node-3:
    container_name: super-node-3
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.3
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.3
      - nextIp=10.1.1.4
    entrypoint: java -jar build/libs/t1-p2p-1.jar

  super-node-4:
    container_name: super-node-4
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.4
    environment:
      - type=SuperNode
      - port=9000
      - ip=10.1.1.4
      - nextIp=10.1.1.1
    entrypoint: java -jar build/libs/t1-p2p-1.jar

  node-1:
    container_name: node-1
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.5
    environment:
      - type=Node
      - ip=10.1.1.5
      - port=9000
      - superNodeIp=10.1.1.1
      - superNodePort=9000
      - dir=Node1Dir
      - terminal=Node1
    volumes:
      - type: bind
        source: ./src/main/java/com/t1/Terminal/Node1.txt
        target: /home/T1-P2P/src/main/java/com/t1/Terminal/Node1.txt
    entrypoint: java -jar build/libs/t1-p2p-1.jar
    
  node-2:
    container_name: node-2
    build: .
    networks:
      distribuida:
        ipv4_address: 10.1.1.6
    environment:
      - type=Node
      - ip=10.1.1.6
      - port=9000
      - superNodeIp=10.1.1.2
      - superNodePort=9000
      - dir=Node2Dir
      - terminal=Node2
    volumes:
      - type: bind
        source: ./src/main/java/com/t1/Terminal/Node2.txt
        target: /home/T1-P2P/src/main/java/com/t1/Terminal/Node2.txt
    entrypoint: java -jar build/libs/t1-p2p-1.jar


networks:
  distribuida:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/8